### PR TITLE
Fix for DTLS connectivity error handling for Linux platform.

### PR DESCRIPTION
**Pull request by yogpan01**
Updating unit tests.

### CODE REVIEW

**Comment by miklis** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by miklis** [comment]
Automatic CI verification build not done, please verify manually.

**Comment by yogpan01** [comment]
@AnttiKauppila Please review

**Comment by AnttiKauppila** [comment]
+1

**Comment by yogpan01** [comment]
rebuild

**Comment by yogpan01** [comment]
Abandoning this PR as proper fix has been done in a separate PR.

**Pull request closed without merging**
